version: "3.7"
services:
  mongodb_container:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USER: root
      - MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
	- 27017:27017
    volumes:
        - mongo_data_container:/data/db

volumes:
  mongo_data_container:

